### ISSUE TITLE
GRIP 1.4.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/sdg-data-donnees-odd#55]
### 1.4.1 Proportion of population living in households with access to basic services

From official UN metadata:

> Basic Services refer to public service provision systems that meet human basic needs including drinking 
water, sanitation, hygiene, energy, mobility, waste collection, health care, education and information 
technologies. The basis services indicator will be therefore based on 9 components. **These components 
are captured in various standalone indicators of the SDGs, which means that the concepts and definitions 
of SDG indicator 1.4.1 will be derived from or are the same as those of these specific SDG indicators.**

#### A breakdown of which components we do and don't report on currently:

- [x] 3.7.1 Proportion of women of reproductive age (aged 15–49 years) who have their need for family planning satisfied with modern methods (_marked N/A_)
- [ ] 3.8.1 Coverage of essential health service (#52)
- [x] 4.1.1 Proportion of children and young people (a) in grades 2/3; (b) at the end of primary; and (c) at the end of lower secondary achieving at least a minimum proficiency level in (i) reading and (ii) mathematics, by sex
- [x] 5.b.1 Proportion of individuals who own a mobile telephone, by sex
- [x] 6.1.1 Proportion of population using safely managed drinking water services
- [x] 6.2.1 Proportion of population using (a) safely managed sanitation services and (b) a hand-washing facility with soap and water (_marked N/A_)
- [x] 7.1.1 Percentage of population with access to electricity 
- [x] 7.1.2 Percentage of population with primary reliance on clean fuels and technology (#53)
- [x] 9.1.1 Proportion of the rural population who live within 2 km of an all-season road (#54)
- [x] 9.c.1 Proportion of population covered by a mobile network, by technology
- [x] 11.2.1 Proportion of population that has convenient access to public transport, by sex, age and persons with disabilities
- [x] 11.6.1 Proportion of municipal solid waste collected and managed in controlled facilities out of total municipal waste generated, by cities

Closing this data gap depends on reporting on **all** these components.

**Comment by JulienSTC** [comment]
This one could be reported as we have most of the series reported already, please update with the data at the national level from the sub-indicators listed above, refer to the metadata to see details.

**Comment by camereb** [comment]
Note: need to finish FR translation in meta for comments & definitions.

**Comment by catherinemichaud** [comment]
Can you confront what we publish with the official metadata, and clean up this ticket please. We publish series that are not what the metadata asks, and some indicator in the list above are checked even if they aren't on the data hub.

**Comment by catherinemichaud** [comment]
This indicator has serious issues. There are geographies under the sex drop down menu, missing data in almost every chart, etc.

**Comment by catherinemichaud** [comment]
- [ ] According to the metadata, Access to clean fuels and technology only includes: SDG 7.1.2 - Percentage of population with primary reliance on clean fuels and technology
- [ ] Basic mobility:  Can you add years before 2023 so that the data points is not on the y-axis. Also, can these series (both under basic mobility)be a bar chart. If not possible to have only this series as bar chart, change all to bar charts. Same for Basic education.
- [ ] Access to basic waste collection system: Please include [Proportion of municipal solid waste collected and managed in controlled facilities out of total municipal waste generated, by cities](https://sdg-data-canada-odd-donnees.github.io/sdg-odd-dev/11-6-1/) and indicate this one is a proxy
- [ ] Basic information services: Please remove years = 0 for 5G (I'm guessing it didn't exists in these years.)

**Comment by catherinemichaud** [comment]
- [ ] Access to basic waste collection system: the Geography doesn't "autoselect".
Comment:
- [ ] EN: Access to basic waste collection system is measured via the proxy series "Total amount of waste sent to disposal via the waste management industry". The UN Global series uses indicator 11.6.1 "Proportion of municipal solid waste collected and managed in controlled facilities out of total municipal waste generated, by cities”.
- [ ] FR: L'accès aux services de base de collecte des déchets est mesuré via la série de substitution "Quantité totale de déchets éliminés dans des installations d'élimination des déchets". La série global des Nations Unies utilise l'indicateur 11.6.1 “Proportion de déchets municipaux solides recueillis et gérés dans des installations contrôlées par rapport au total des déchets municipaux solides générés, par ville”.

**Comment by catherinemichaud** [comment]
- [ ] Access to basic education should default to sex = total

**Comment by tristanmenard** [comment]
Leaving this ticket open so that we remember to come back to the data_start_value issue with this indicator

**Comment by tristanmenard** [comment]
Fixed with update to latest open-sdg 2.4.0 dev branch a while back
